name: Extract Users from All JSON in 'c'

on:
  push:
    branches:
      - main  # your branch

jobs:
  extract-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run extraction script
        run: python read_users.py

      - name: Upload combined_users.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: combined-users
          path: combined_users.json
