name: Extract Users Preserving Structure

on:
  push:
    branches:
      - main

jobs:
  extract-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run extraction script
        run: python read_users.py

      - name: Upload extracted_users folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extracted-users-folder
          path: extracted_users
